export const ActionTypes = {
  SET_MATERI: "SET_MATERI",
  SET_BAB: "SET_BAB",
  SET_SOAL: "SET_SOAL",

  SET_PENGAJAR: "SET_PENGAJAR",

  SET_PRODUK: "SET_PRODUK",

  SET_CUSTOMER: "SET_CUSTOMER",

  SET_ORDER: "SET_ORDER",

  SET_MODAL: "SET_MODAL",
  SET_TITLE: "SET_TITLE",
  SET_ALERT: "SET_ALERT",
  SET_SESSION: "SET_SESSION",
};
